dist: trusty
sudo: required
services:
   - docker
   
env:
  global:
    - ROOTDIR="$TRAVIS_BUILD_DIR"
    
before_install:
  - # docker build -t companion_image .
  - docker pull $DOCKER_IMAGE
  - docker tag $DOCKER_IMAGE companion_image
  - docker run -dit -v $TRAVIS_BUILD_DIR:/tmp/companion --name companion_container companion_image /bin/bash
  - sleep 5
  - docker container ls
  - docker exec companion_container ls /tmp/companion
  - docker exec companion_container /bin/bash -c 'apt-get install --yes -q default-jre curl wget'
  - docker exec companion_container /bin/bash -c 'cd /tmp/companion; curl -fsSL get.nextflow.io | bash'
  - docker exec companion_container /bin/bash -c 'cd /tmp/companion; wget -q http://geneontology.org/ontology/go.obo'
  - docker exec companion_container /bin/bash -c 'cd /tmp/companion; wget -q http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz'
  - docker exec companion_container /bin/bash -c 'cd /tmp/companion; zcat Pfam-A.hmm.gz | test/split-hmm.lua 1000 > Pfam-A.hmm'
  - docker exec companion_container /bin/bash -c 'cd /tmp/companion; hmmpress Pfam-A.hmm && rm -f Pfam-A.hmm'

cache:
  directories:
    - work
    
script:
  - docker exec companion_container /bin/bash -c 'cd /tmp/companion/test/testsuite; ./testsuite.rb -threads 2'
  - travis_wait docker exec companion_container /bin/bash -c 'cd /tmp/companion; ./nextflow -c loc_travis.config -c params_default.config run annot.nf --do_circos=false'
  - travis_wait docker exec companion_container /bin/bash -c 'cd /tmp/companion; ./nextflow -c loc_travis.config -c params_default.config run annot.nf --do_circos=false --run_exonerate=true'
  - travis_wait docker exec companion_container /bin/bash -c 'cd /tmp/companion; ./nextflow -c loc_travis.config -c params_default.config run annot.nf --do_circos=false --do_pseudo=false'
  - travis_wait docker exec companion_container /bin/bash -c 'cd /tmp/companion; ./nextflow -c loc_travis.config -c params_default.config run annot.nf --do_circos=false --run_snap=false'
